version: 2
jobs:
  build:
    working_directory: ~/go-demo
    docker:
      - image: circleci/golang:1.8.1
      - image: postgres:9.6.2
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "main.go" }}
          paths:
            - "/go"
  test:
    working_directory: ~/go-demo
    docker:
      - image: circleci/golang:1.8.1
      - image: postgres:9.6.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "main.go" }}
      - run: go test -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build