version: 2
jobs:
  build:
    working_directory: ~/go-demo
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/go-demo
      - image: postgres:9.6.2
      
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v
      - persist_to_workspace:
          root: ~/go-demo
          paths:
            - src/
  test:
    working_directory: ~/go-demo
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/go-demo
      - image: postgres:9.6.2
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: src/
      - run: go test -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build